var annotated_dup =
[
    [ "Pathfinding", "namespace_pathfinding.html", [
      [ "INode", "interface_pathfinding_1_1_i_node.html", "interface_pathfinding_1_1_i_node" ]
    ] ],
    [ "AIPlayer", "class_a_i_player.html", null ],
    [ "AudioManagement", "class_audio_management.html", "class_audio_management" ],
    [ "Card", "class_card.html", "class_card" ],
    [ "CardDisplayer", "class_card_displayer.html", "class_card_displayer" ],
    [ "Deck", "class_deck.html", null ],
    [ "DiceRollMenu", "class_dice_roll_menu.html", "class_dice_roll_menu" ],
    [ "EnemyNode", "class_enemy_node.html", "class_enemy_node" ],
    [ "Flasher", "class_flasher.html", "class_flasher" ],
    [ "FriendlyNode", "class_friendly_node.html", "class_friendly_node" ],
    [ "Hand", "class_hand.html", "class_hand" ],
    [ "LocalPlayer", "class_local_player.html", "class_local_player" ],
    [ "Map", "class_map.html", "class_map" ],
    [ "MapEditor", "class_map_editor.html", "class_map_editor" ],
    [ "MatchManager", "class_match_manager.html", "class_match_manager" ],
    [ "MenuManagement", "class_menu_management.html", "class_menu_management" ],
    [ "MultiObjectPool", "class_multi_object_pool.html", "class_multi_object_pool" ],
    [ "NetworkConnection", "class_network_connection.html", "class_network_connection" ],
    [ "NetworkManagement", "class_network_management.html", "class_network_management" ],
    [ "NetworkPlayer", "class_network_player.html", "class_network_player" ],
    [ "ObjectPoolInfoStorage", "class_object_pool_info_storage.html", "class_object_pool_info_storage" ],
    [ "OptionsManagement", "class_options_management.html", "class_options_management" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "PlayerInfoHandler", "class_player_info_handler.html", "class_player_info_handler" ],
    [ "PlayerInputHandler", "class_player_input_handler.html", "class_player_input_handler" ],
    [ "PlayOptionsManagement", "class_play_options_management.html", "class_play_options_management" ],
    [ "PlayScreenNetworkDataCommunicator", "class_play_screen_network_data_communicator.html", "class_play_screen_network_data_communicator" ],
    [ "PolygonUtility", "class_polygon_utility.html", null ],
    [ "RawImageMoveOverTime", "class_raw_image_move_over_time.html", "class_raw_image_move_over_time" ],
    [ "SpriteFetcher", "class_sprite_fetcher.html", "class_sprite_fetcher" ],
    [ "Territory", "class_territory.html", "class_territory" ],
    [ "TerritoryHelper", "class_territory_helper.html", null ],
    [ "TextureNode", "class_texture_node.html", "class_texture_node" ],
    [ "TransitionControl", "class_transition_control.html", "class_transition_control" ],
    [ "TroopTransporter", "class_troop_transporter.html", "class_troop_transporter" ],
    [ "UIManagement", "class_u_i_management.html", "class_u_i_management" ],
    [ "VisualCard", "class_visual_card.html", "class_visual_card" ],
    [ "WinScreenControl", "class_win_screen_control.html", "class_win_screen_control" ]
];